on: 
  pull_request:
    types: [labeled, unlabeled]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign a PR to project based on label
    steps:
      - name: Assign to project
        uses: alexh97/github-actions/project-assigner@b23e906017e8bab6ad2f9718ff1e0320b06061bd
        id: project_assigner
        with:
          issue-mappings: |
            [
            ]
            
          ghToken: ${{ secrets.PROJECT_ASSIGNER_TOKEN }}

#              {"label": "Test", "projectName": "Test", "columnId": 8230518},
#              {"label": "bug", "projectName": "Test", "columnId": 8230520},
#              {"label": "invalid", "projectName": "Test", "columnId": 8230521}
